# Generated by Django 4.1.7 on 2023-02-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('TeamId', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='password', max_length=500)),
                ('UserName', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('Role', models.CharField(default='Worker', max_length=500)),
                ('Admin', models.BooleanField(default=False)),
                ('TeamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.teams')),
            ],
        ),
    ]
